# Generated by Django 4.1.4 on 2023-01-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcedureProtocolVersion',
            new_name='ProtocolVersionStep',
        ),
        migrations.DeleteModel(
            name='ComponentAmount',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='name',
            new_name='component_name',
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('Equipment', 'EQUIPMENT'), ('Reagent', 'REAGENT'), ('Chemical', 'CHEMICAL'), ('Consumable', 'CONSUMABLE'), ('Software', 'SOFTWARE'), ('Other', 'OTHER')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='procedurecomponent',
            name='amount',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedurecomponent',
            name='amount_unit',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedurecomponent',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.procedure'),
        ),
    ]
