# Generated by Django 4.1.4 on 2023-01-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_rename_procedureprotocolversion_protocolversionstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurecomponent',
            name='amount_unit',
            field=models.CharField(choices=[('mL', 'MILILITRE'), ('uL', 'MICROLITRE'), ('L', 'LITRE'), ('g', 'GRAM'), ('mg', 'MILIGRAM'), ('ug', 'MICROGRAM'), ('each', 'EACH'), ('Other', 'OTHER')], default='Other', max_length=10),
        ),
    ]
