# Generated by Django 4.1.4 on 2023-01-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_alter_procedurecomponent_amount_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolversion',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_protocol', to='protocol.protocol'),
        ),
    ]
